name: Build and deploy the Streamlit Streaming App on Azure App Services
env: 
  AZURE_WEBAPP_NAME: Streamlit-Streaming-App
  AZURE_WEBAPP_PACKAGE_PATH: './streamlit-app/src/'
  PY_VERSION: '3.9'

on: 
  push: 
    branches: 
      -main 
    workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2 
      
      - name: Set up Python version 
        uses: actions/setup-python@v1 
        with: 
          python-version: ${{ env.PY_VERSION}}
      
      - name: create and start virtual environment 
        run: | 
          cd ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          python -m venv .app-venv/
          source .app-venv/bin/activate
      
      - name: Install Dependencies 
        run: | 
          cd ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          pip install -r requirements.txt
      
      # Optional: Add a step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs 
        uses: actions/upload-artifact@v2
        with: 
          name: streamlit-stream-app
          path: | 
            ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
            !.app-venv/
  
  deploy: 
    runs-on: ubuntu-latest 
    needs: build 
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps: 
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: streamlit-stream-app
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
    
    - name: 'Deploy to Azure App Services'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STREAMLIT_STREAMING }}
          